%% Author: Igor compiler
%% Compiler version: igorc 1.1.4
%% DO NOT EDIT THIS FILE - it is machine generated

-record(status, {
    result = false :: boolean(),
    error = <<"unknown_error">> :: binary()
}).

