%% Author: Igor compiler
%% Compiler version: igorc 2.0.0
%% DO NOT EDIT THIS FILE - it is machine generated

-record(zeus_instance, {
    id :: binary() | '_',
    key :: binary() | '_',
    title :: binary() | '_',
    api_root :: binary() | '_',
    api_key :: binary() | '_'
}).

-record(zeus_user, {
    id :: binary() | '_',
    login :: binary() | '_',
    realm :: atom() | '_',
    admin_roles = [] :: [atom()] | '_'
}).

-record(zeus_role, {
    id :: binary() | '_',
    login :: binary() | '_',
    realm :: atom() | '_',
    instance_id :: binary() | 'undefined' | '_',
    roles :: [atom()] | '_'
}).

-record(zeus_realm, {
    id :: binary() | '_',
    name :: atom() | '_',
    instance_id :: binary() | 'undefined' | '_',
    roles = [] :: [atom()] | '_'
}).

-record(reply_status, {
    result = true :: boolean(),
    error :: binary() | 'undefined',
    invalid_fields :: [binary()] | 'undefined'
}).

