%% Author: Igor compiler
%% Compiler version: igorc 2.0.0
%% DO NOT EDIT THIS FILE - it is machine generated

-record(privilege_manage_users, {
    roles :: [zeus_shared_protocol:role()]
}).

-record(role_info, {
    role :: zeus_shared_protocol:role(),
    title :: binary(),
    description :: binary(),
    privileges :: [zeus_shared_protocol:privilege()]
}).

-record(instance, {
    key :: binary(),
    title :: binary(),
    icon :: binary(),
    roles :: [zeus_shared_protocol:role_info()]
}).

-record(menu, {
    items = [] :: [zeus_shared_protocol:menu_item()]
}).

-record(menu_item, {
    route :: binary(),
    items = [] :: [zeus_shared_protocol:menu_item()]
}).

-record(page, {
    title :: binary(),
    icon :: binary() | 'undefined',
    layout_url :: binary(),
    data_url :: binary() | 'undefined',
    is_websocket = false :: boolean(),
    data :: json:json() | 'undefined'
}).

-record(search_result, {
    route :: binary()
}).

-record(request, {
    enabled :: zeus:binding() | 'undefined',
    method = get :: zeus_shared_protocol:method(),
    data_url :: binary(),
    args = [] :: igor_types:dict(binary(), zeus:binding()),
    body :: zeus:json_binding() | 'undefined',
    result :: zeus:binding() | 'undefined',
    on_complete :: zeus_shared_protocol:action() | 'undefined'
}).

-record(navigate, {
    enabled :: zeus:binding() | 'undefined',
    route :: binary()
}).

-record(reload, {
    enabled :: zeus:binding() | 'undefined'
}).

-record(popup, {
    enabled :: zeus:binding() | 'undefined',
    layout_url :: binary() | 'undefined',
    content_template :: zeus_shared_protocol:element() | 'undefined',
    data_url :: binary() | 'undefined',
    content :: zeus:binding() | 'undefined',
    is_context = true :: boolean(),
    width :: igor_types:int() | 'undefined'
}).

-record(assign, {
    enabled :: zeus:binding() | 'undefined',
    path :: zeus:binding(),
    value :: zeus:binding()
}).

-record(element_layout, {
    element :: zeus_shared_protocol:element() | 'undefined'
}).

-record(horizontal, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    items :: [zeus_shared_protocol:element()]
}).

-record(vertical, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    items :: [zeus_shared_protocol:element()]
}).

-record(listing, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    item_template :: zeus_shared_protocol:element(),
    items :: zeus:binding(),
    show_separator = false :: boolean()
}).

-record(label, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    text :: zeus:binding(),
    color :: zeus:binding() | 'undefined'
}).

-record(block, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    caption_template :: zeus_shared_protocol:element() | 'undefined',
    content_template :: zeus_shared_protocol:element(),
    caption :: zeus:binding() | 'undefined',
    content :: zeus:binding() | 'undefined'
}).

-record(table_column, {
    caption_template :: zeus_shared_protocol:element() | 'undefined',
    content_template :: zeus_shared_protocol:element() | 'undefined',
    caption :: zeus:binding(),
    content :: zeus:binding() | 'undefined',
    align :: zeus:binding() | 'undefined',
    sort_by :: zeus:binding() | 'undefined',
    sort_dir :: zeus:binding() | 'undefined'
}).

-record(table, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    columns = [] :: [zeus_shared_protocol:table_column()],
    rows :: zeus:binding() | 'undefined',
    url :: binary() | 'undefined',
    pagination = true :: boolean(),
    compact = false :: boolean()
}).

-record(text_edit, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    placeholder :: binary() | 'undefined',
    text :: zeus:binding(),
    kind = text :: zeus_shared_protocol:text_edit_kind(),
    multiline = false :: boolean()
}).

-record(button, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    text :: zeus:binding(),
    on_click :: zeus_shared_protocol:action()
}).

-record(link, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    text :: zeus:binding(),
    on_click :: zeus_shared_protocol:action()
}).

-record(layout, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    layout_url :: binary(),
    content :: zeus:binding()
}).

-record(date_time_picker, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    date_time :: zeus:binding(),
    mode = datetime :: zeus_shared_protocol:date_time_mode()
}).

-record(time_interval, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    interval :: zeus:binding(),
    mode = milliseconds :: zeus_shared_protocol:time_span()
}).

-record(image, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    source :: zeus:binding(),
    on_click :: zeus_shared_protocol:action() | 'undefined',
    source_type = instance :: zeus_shared_protocol:source_type(),
    scale = false :: boolean()
}).

-record(chart, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    caption :: zeus:binding() | 'undefined',
    source :: zeus:binding(),
    chart_type = bar :: zeus_shared_protocol:chart_type(),
    series :: [zeus:binding()],
    flat = false :: boolean()
}).

-record(image_button, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    icon :: zeus:binding(),
    tooltip :: zeus:binding() | 'undefined',
    on_click :: zeus_shared_protocol:action()
}).

-record(checkbox, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    checked :: zeus:binding(),
    text :: zeus:binding(),
    color :: zeus:binding() | 'undefined',
    on_change :: zeus_shared_protocol:action()
}).

-record(combobox, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    items :: zeus:binding(),
    caption :: zeus:binding(),
    selected :: zeus:binding(),
    on_change :: zeus_shared_protocol:action()
}).

-record(inplace_text_edit, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    text :: zeus:binding(),
    on_change :: zeus_shared_protocol:action()
}).

-record(separator, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined'
}).

-record(html, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    content :: zeus:binding()
}).

-record(tab_item, {
    title :: binary(),
    icon = <<"icon-info-sign">> :: binary(),
    layout_url :: binary(),
    data_url :: binary() | 'undefined',
    is_websocket = false :: boolean()
}).

-record(tabs, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    items = [] :: [zeus_shared_protocol:tab_item()]
}).

-record(radio_item, {
    template :: zeus_shared_protocol:element() | 'undefined',
    caption :: zeus:binding(),
    value :: zeus:binding()
}).

-record(radiogroup, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    items = [] :: [zeus_shared_protocol:radio_item()],
    vertical_order = true :: boolean(),
    value :: zeus:binding()
}).

-record(property_grid, {
    visible :: zeus:binding() | 'undefined',
    on_load :: zeus_shared_protocol:action() | 'undefined',
    on_hover :: zeus_shared_protocol:popup() | 'undefined',
    collapsed = false :: boolean(),
    value :: zeus:binding()
}).

